# Base image
FROM debian

# Activer les privilèges root
USER root

# Installer iptables et outils réseau
RUN apt-get update && apt-get install -y iproute2 iputils-ping iptables 

# Copier le script d'init
COPY router-init.sh /etc/router-init.sh
RUN chmod +x /etc/router-init.sh


# Lancer le script au démarrage
CMD ["/etc/router-init.sh"]

