# Base image
FROM debian

# Activer les privilèges root
USER root

# Installer les outils réseau (ping, iproute2)
RUN apt-get update && apt-get install -y iproute2 iputils-ping curl

# Ajouter le script d'initialisation
COPY pc-init.sh /etc/pc-init.sh
RUN chmod +x /etc/pc-init.sh

# Lancer le script au démarrage
CMD ["/etc/pc-init.sh"]

